### ISSUE TITLE
请问项目还能用吗？

### ISSUE THREAD

**Issue by robyle** [passed-by/ppkao#1]
你好，请问项目是怎么使用的，还能正常查答案吗？

**Comment by passed-by** [comment]
不好意思,已经不能了,你可以自己试试,它的思路也是差不多的

**Comment by robyle** [comment]
> 不好意思,已经不能了,你可以自己试试,它的思路也是差不多的

嗯，请问你有空采集数据么。我这边有个需求想采集这个平台的数据需求。不知道你是否有空。

**Comment by passed-by** [comment]
换个位置聊吧   vx:wjyzdn12
